# File: CP494-project/docker-compose.yml
# This runs n8n in a container

version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: cp494-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./n8n-workflows:/workflows
      - ./database:/database
    restart: unless-stopped